### ISSUE TITLE
link to Syck is broken

### ISSUE THREAD

**Issue by jwuttke** [yaml/www.yaml.org#27] opened 2018-04-26 15:48 UTC
Projects >  C/C++ Libraries > Syck:

link goes to unrelated _why impersonator

**Comment by ixti** [comment] 2018-06-20 01:46
Duplicate of: yaml/yaml#40

**Comment by perlpunk** [comment] 2020-05-01 14:01
I moved the link to a HTML comment.

**Closed by perlpunk** 2020-05-01 14:01 UTC
